# Generated by Django 4.2.10 on 2024-02-22 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearn_app', '0005_customtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_token', to='elearn_app.customuser'),
        ),
    ]
