# Generated by Django 4.0 on 2024-02-26 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearn_app', '0010_remove_course_end_date_remove_course_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_type', models.CharField(choices=[('Reading', 'Reading'), ('Test', 'Test'), ('Video', 'Video'), ('Audio', 'Audio')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('text_content', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/topics/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn_app.course')),
            ],
        ),
    ]
