# Generated by Django 4.0 on 2024-02-26 11:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearn_app', '0011_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('option_b', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('option_c', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('option_d', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn_app.course')),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn_app.topic')),
            ],
        ),
    ]
