# Generated by Django 4.0 on 2024-02-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn_app', '0013_rename_course_id_test_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
