# Generated by Django 4.0 on 2024-02-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn_app', '0015_teacherprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_profiles/'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
