# Generated by Django 4.0 on 2024-02-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn_app', '0017_studentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='courses/'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='topics/'),
        ),
    ]
