# Generated by Django 4.0 on 2024-03-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn_app', '0022_updatehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatehistory',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
